// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAryqDlg3eqfKRrSEVunIlEC7GpN3pqOQ',
    appId: '1:35762292847:web:c117c7e791b166f272659a',
    messagingSenderId: '35762292847',
    projectId: 'multi-vendor-ali-jawad',
    authDomain: 'multi-vendor-ali-jawad.firebaseapp.com',
    storageBucket: 'multi-vendor-ali-jawad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh3LGvUwzSJZrR176CBhkerLGgu8kwGKg',
    appId: '1:35762292847:android:59ccda39d156002c72659a',
    messagingSenderId: '35762292847',
    projectId: 'multi-vendor-ali-jawad',
    storageBucket: 'multi-vendor-ali-jawad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmqqmFlbAOlo4ij_t_wY9tZGoneTy0S7w',
    appId: '1:35762292847:ios:b2d4525795e85ff372659a',
    messagingSenderId: '35762292847',
    projectId: 'multi-vendor-ali-jawad',
    storageBucket: 'multi-vendor-ali-jawad.appspot.com',
    iosClientId: '35762292847-t8ac1kobnvfj1tc8alaeeq2k5ek55bt9.apps.googleusercontent.com',
    iosBundleId: 'com.example.multivendorapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmqqmFlbAOlo4ij_t_wY9tZGoneTy0S7w',
    appId: '1:35762292847:ios:8a3946aa04e6416872659a',
    messagingSenderId: '35762292847',
    projectId: 'multi-vendor-ali-jawad',
    storageBucket: 'multi-vendor-ali-jawad.appspot.com',
    iosClientId: '35762292847-i3evs63qqhdhve2bklpoo0sc97mhtj6k.apps.googleusercontent.com',
    iosBundleId: 'com.example.multivendorapp.RunnerTests',
  );
}
